# Generated by Django 3.0.6 on 2020-11-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
