# Generated by Django 3.0.6 on 2020-11-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('govt_id', 'Government ID'), ('passport', 'Passport Photograph')], max_length=100),
        ),
    ]
