# Generated by Django 3.0.6 on 2021-01-26 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='acct_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wire',
            name='acct_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tfs', to=settings.AUTH_USER_MODEL),
        ),
    ]
