# Generated by Django 3.0.6 on 2021-02-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20210126_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wire',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='wire',
            name='tf_code',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
